services:
  flask-app:
    build: ./flask  # Specifying Dockerfile is unnecessary as it defaults to that
    container_name: flask-app
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - flask-prometheus-network

  prometheus:
    build:
      context: ./prom  # Path to the Prometheus Dockerfile
      dockerfile: Dockerfile.prometheus # Need to specify the actual name here
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - flask-prometheus-network
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - flask-prometheus-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  flask-prometheus-network:
    driver: bridge

volumes:
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      device: ./grafana-storage
      o: bind